# Dockerfile for https://hub.docker.com/r/giorgio14/pelican/
FROM ruby:2.5

COPY requirements.txt ./requirements.txt

RUN apt-get update && apt-get install -y apt-utils python python-pip && \
    pip install -r requirements.txt && \
    gem install sass
